apiVersion: v1
kind: Service
metadata:
  name: authapp-service
spec:
  selector:
    app: authapp
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: usersapp-service
spec:
  selector:
    app: usersapp
  ports:
    - port: 8082
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: pgadminapp-service
spec:
  selector:
    app: pgadminapp
  ports:
    - port: 5050
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgresapp-service
spec:
  selector:
    app: postgresapp
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/pgadmin
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
spec:
  volumeName: pgadmin-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresapp-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgres
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresapp-pvc
spec:
  volumeName: postgresapp-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapp
spec:
  selector:
    matchLabels:
      app: authapp
  template:
    metadata:
      labels:
        app: authapp
    spec:
      containers:
      - name: authapp
        image: sandeepbhanja/zerotrustapiauth:latest
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresapp
  template:
    metadata:
      labels:
        app: postgresapp
    spec:
      containers:
      - name: postgresapp
        image: postgres:latest
        imagePullPolicy: Always
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "password"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgresapp-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadminapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadminapp
  template:
    metadata:
      labels:
        app: pgadminapp
    spec:
      containers:
      - name: pgadminapp
        image: dpage/pgadmin4:latest
        imagePullPolicy: Always
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: "sandeep@gmail.com"
          - name: PGADMIN_DEFAULT_PASSWORD
            value: "password"
        volumeMounts:
          - mountPath: /var/lib/pgadmin/sessions
            name: pgadmin-storage
      volumes:
        - name: pgadmin-storage
          persistentVolumeClaim:
            claimName: pgadmin-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapp
spec:
  selector:
    matchLabels:
      app: usersapp
  template:
    metadata:
      labels:
        app: usersapp
    spec:
      containers:
      - name: usersapp
        image: sandeepbhanja/zerotrustapiusers:latest
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: sandeepbhanja/zerotrustapigateway:latest
        imagePullPolicy: Always
---